### ISSUE TITLE
SQLAlchemy Instrumentation: `enable_commenter` can't be disabled.

### ISSUE THREAD

**Issue by tveastman** [open-telemetry/opentelemetry-python-contrib#1368]
Based on the [documentation](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/sqlalchemy/sqlalchemy.html#usage), you'd assume that:

```python
SQLAlchemyInstrumentor().instrument(enable_commenter=False)
```

Would enable instrumentation but disable the statement commenter, but it doesn't work. It looks like you can't disable the sql commenter unless you are providing the `engine` keyword as well, which requires you to have already created the engine at that point in your code path.

It looks like the `enable_commenter` and related kwargs need to be passed to the `_wrap_create_engine` function?

**Comment by srikanthccv** [comment]
>It looks like the enable_commenter and related kwargs need to be passed to the _wrap_create_engine function?

Correct, and pass it to `EngineTracer` which enables commenter by default.

**Comment by avzis** [comment]
hi, can you assign this to me? thanks :)

**Comment by avzis** [comment]
I did the change to pass `enable_commenter` to `EngineTracer`.

But the problem can still happen, because the functionality of `enable_commenter` depends on calling EngineTracer.

If you initiate the instrumentation using an existing engine, the `instrument(engine)` will wrap the engine with `EngineTracer`
But if you initiate the instrumentation without an engine, and create an engine later on, you will have to wrap that engine manually in order to enable/disable the `enable_commenter` like this:

```
        SQLAlchemyInstrumentor().instrument()
        engine = create_engine("sqlite:///:memory:")
        EngineTracer(
            _get_tracer(self.tracer_provider), engine, enable_commenter=True
        )
```

This basically means that you either have to initiate the instrumentation using an existing engine, or manually call `EngineTracer`

I would like to hear opinions on how to solve this..
