### ISSUE TITLE
Please add support for mysqlclient connector

### ISSUE THREAD

**Issue by bigon** [open-telemetry/opentelemetry-python-contrib#1649]
Hello,

ATM it seems that the mysql instrumentation only support `pymysql` and `mysql-connector-python`, but for what I can see SQLAlchemy uses, by default `mysqldb` (aka `mysqlclient`)

Shouldn't `mysqlclient` be added so instrumentation works OOTB?

Note that SQLAlchemy explicitly says that `mysql-connector-python` is not supported:

```
    The MySQL Connector/Python DBAPI has had many issues since its release,
    some of which may remain unresolved, and the mysqlconnector dialect is
    **not tested as part of SQLAlchemy's continuous integration**.
    The recommended MySQL dialects are mysqlclient and PyMySQL.
```

**Comment by rahuldimri** [comment]
We want to try on this. Could you please assign this task to me. Thanks

**Comment by Fenkiou** [comment]
Hello, I've created a PR to address that issue because I need this at work.

But I realized that I could just use the dbapi instrumentation like this

`trace_integration(MySQLdb, "connect", "mysql")`

So I am wondering, why do we need dedicated instrumentation librairies if the dbapi one is able to handle those that complies with PEP-0249?
