### ISSUE TITLE
fix fastapi instrumentation tests for version 0.91

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1665]
The tests for FastAPI instrumentation failing since the new release of FastAPI ~= 0.91. All the tests pass except the test, which adds the middleware after the app starts. Fix the test and relax the version requirement introduced in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1664

**Comment by Akochavi** [comment]
Can you assign me please?

**Comment by phillipuniverse** [comment]
@Akochavi how far along on the fix are you? I have some bandwidth that I could take this on.

I will also say that in general, I think that library version changes like the one in #1664 should be called out very explicitly in the changelog. In my scenario, I updated FastAPI to 0.93 but had no idea that otel stopped instrumenting since all the failures on version mismatches are silent.

Maybe there is an opportunity to be able to tell otel which libraries _must_ be instrumented? For instance, if I have _any_ version of FastAPI in my environment, I expect it to be instrumented. Same with Django or any other library that I am using even if there are version mismatches.

**Comment by Akochavi** [comment]
@phillipuniverse Hi, the fix is already merged.

**Comment by phillipuniverse** [comment]
Ah found it, #1710.
