### ISSUE TITLE
Update gRPC server status code to span status code mapping

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-python-contrib#1756]
Spec ref: https://github.com/open-telemetry/opentelemetry-specification/pull/3333

**Comment by chenikabukes** [comment]
Hi @srikanthccv I'd like to work on this!

**Comment by neomatrix3** [comment]
Hello @srikanthccv I would like to contribute to this project

**Comment by srikanthccv** [comment]
This is already taken. You can find other good-first-issues not assigned to anybody here https://github.com/open-telemetry/opentelemetry-python-contrib/issues?q=is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee

**Comment by neomatrix3** [comment]
thanks

**Comment by FilipNikolovski** [comment]
Any movement on this issue? Would be happy to help here.

**Comment by ccorbacho** [comment]
For anyone picking this up (as I've been reviewing the same issue in the Java implementation) -

The problem in Python land is in the handling of grpc.RpcError when it gets thrown:
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/_client.py#L154

https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/_client.py#L212

As per the upstream docs, anything that doesn't return OK will throw RpcError():
https://grpc.github.io/grpc/python/grpc.html#grpc-exceptions

However, rather than just treating that as an error, as the code currently does, we need to be checking the status first, and then decide if that status is actually one we should mark the span as error or not (e.g. NOT_FOUND should not mark the span as an error).

**Comment by FilipNikolovski** [comment]
@srikanthccv I'd be happy to pick this up.
