### ISSUE TITLE
Celery docker-tests check started failing

### ISSUE THREAD

**Issue by jeremydvoss** [open-telemetry/opentelemetry-python-contrib#1837]
Contrib sibling of [this](https://github.com/open-telemetry/opentelemetry-python/issues/3338)

**Describe your environment** Checks that previously passed have started failing and block [my pr](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1823):

```
=================================== FAILURES ===================================
__________________________ test_fn_exception_expected __________________________

celery_app = <Celery celery.tests at 0x7fbb1d780b50>
memory_exporter = <opentelemetry.sdk.trace.export.in_memory_span_exporter.InMemorySpanExporter object at 0x7fbb1d926f80>

    def test_fn_exception_expected(celery_app, memory_exporter):
        @celery_app.task(throws=(MyException,))
        def fn_exception():
            raise MyException("Task class is failing")
    
        result = fn_exception.apply()
    
        assert result.failed() is True
        assert "Task class is failing" in result.traceback
    
        spans = memory_exporter.get_finished_spans()
        assert len(spans) == 1
    
        span = spans[0]
    
>       assert span.status.is_ok is True
E       assert False is True
E        +  where False = <opentelemetry.trace.status.Status object at 0x7fbb1d7d6d40>.is_ok
E        +    where <opentelemetry.trace.status.Status object at 0x7fbb1d7d6d40> = <opentelemetry.sdk.trace.ReadableSpan object at 0x7fbb1d7d7b20>.status

celery/test_celery_functional.py:306: AssertionError
______________________ test_class_task_exception_excepted ______________________

celery_app = <Celery celery.tests at 0x7fbb1d6c9240>
memory_exporter = <opentelemetry.sdk.trace.export.in_memory_span_exporter.InMemorySpanExporter object at 0x7fbb1d683910>

    def test_class_task_exception_excepted(celery_app, memory_exporter):
        class BaseTask(celery_app.Task):
            throws = (MyException,)
    
            def run(self):
                raise MyException("Task class is failing")
    
        task = BaseTask()
        # register the Task class if it's available (required in Celery 4.0+)
        register_task = getattr(celery_app, "register_task", None)
        if register_task is not None:
            register_task(task)
    
        result = task.apply()
    
        assert result.failed() is True
        assert "Task class is failing" in result.traceback
    
        spans = memory_exporter.get_finished_spans()
        assert len(spans) == 1
    
        span = spans[0]
    
>       assert span.status.is_ok is True
E       assert False is True
E        +  where False = <opentelemetry.trace.status.Status object at 0x7fbb1d6fb910>.is_ok
E        +    where <opentelemetry.trace.status.Status object at 0x7fbb1d6fb910> = <opentelemetry.sdk.trace.ReadableSpan object at 0x7fbb1d6fbc40>.status

celery/test_celery_functional.py:446: AssertionError
```

**Steps to reproduce**
Make a pr

**What is the expected behavior?**
Checks pass

**What is the actual behavior?**
Checks fail

**Additional context**
Possibly related to https://github.com/open-telemetry/opentelemetry-python-contrib/issues/653

**Comment by jeremydvoss** [comment]
Likely because a new version of celery was just released
https://pypi.org/project/celery/#history

**Comment by shalevr** [comment]
Do you work on this issue?

**Comment by shalevr** [comment]
It is indeed started because of the new celery version(5.3)
but I think the test was wrong in the first place.
the test failed for https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2edcc21ea205f213b2b5aedae72fff8404c3071d/tests/opentelemetry-docker-tests/tests/celery/test_celery_functional.py#L306
and
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2edcc21ea205f213b2b5aedae72fff8404c3071d/tests/opentelemetry-docker-tests/tests/celery/test_celery_functional.py#L307
but in this test we test exception handling, so if I understand this correctly, it should test is_ok=false and StatusCode.Error

**Comment by shalevr** [comment]
It probably changed after this PR
https://github.com/celery/celery/pull/8149

**Comment by shalevr** [comment]
the einfo exception changed from MyException(for out test) to ExceptionWithTraceBace
and that's why this condition no longer true
 
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/2edcc21ea205f213b2b5aedae72fff8404c3071d/instrumentation/opentelemetry-instrumentation-celery/src/opentelemetry/instrumentation/celery/__init__.py#LL254C3-L254C3

**Comment by ocelotl** [comment]
This is pretty much blocking CI, assigning to myself and investigating.

**Comment by shalevr** [comment]
There is PR on this issue #1841 
I think that the test was wrong in the first place
@ocelotl please look at it
