### ISSUE TITLE
Docker tests are failing with AttributeError: module snappy has no attribute compress

### ISSUE THREAD

**Issue by lonewolf3739** [open-telemetry/opentelemetry-python-contrib#313]
This has been happening for a while; noticed some inconsistent behaviour but more frequent recently. Need to look into it and fix.

**Comment by codeboten** [comment]
Thanks for opening this issue, I noticed this today :(

**Comment by haarakdy** [comment]
I get the same problem when deploying the opentelemetry-exporter-prometheus-remote-write
Please see https://github.com/open-telemetry/opentelemetry-python-contrib/pull/314#issuecomment-1132851423

Is the problem fixed in the master?
How do I install the GIT version of opentelemetry-exporter-prometheus-remote-write using pip?
Thanks!

**Comment by larytet** [comment]
https://github.com/larytet-py/opentelemetry_exporter_prometheus_remote_write/commit/dd84c6fce4f127b97ac14038d820984968b5a256
