### ISSUE TITLE
 [Requests] Replace span name callback with request and response hooks

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-python-contrib#411]
Requests instrumentation accepts a span name callback which should be replaced with more generic request/response callbacks (hooks).

Details: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/408

**Comment by NickSulistio** [comment]
I can take on this issue.

cc @alolita

**Comment by lzchen** [comment]
@NickSulistio 
Are you still interested in taking this on?

**Comment by NickSulistio** [comment]
@lzchen

Yeah! Sorry for the delays, I can get it done this week.

**Comment by ryokather** [comment]
Hey @lzchen just wanted to confirm that this is still open since I'm cleaning up the remaining instrumentations without hooks :) (https://github.com/open-telemetry/opentelemetry-python-contrib/issues/412).

cc: @alolita

**Comment by lzchen** [comment]
If you are working on all of the instrumentations that is great! We just have individual tasks for the hooks so be sure to link your PR to each when you submit it.

**Comment by lzchen** [comment]
@ryokather 
Do you have plans on adding hooks for the requests instrumentation?

**Comment by ryokather** [comment]
Hi @lzchen. I believe in my previous PR I investigated into this and found out that implementing hooks on the requests instrumentation isn't easily achievable because the wrapper for Session.request provides no ability to access a request-like object which is necessary for a request_hook. I left it in case anyone else has a better idea!

**Comment by federicobond** [comment]
Hi, I have been investigating this issue and apparently we could remove the instrumentation of Session.request and leave only Session.send ([request goes through send anyway](https://github.com/psf/requests/blob/e90852d20c9bc44c465e55234c01432711627d94/requests/sessions.py#LL587C8-L587C46)).

When you remove the instrumentation for request only one test fails: `test_invalid_url`. I went to look at how other instrumentations handle this case and, at least for the ones I checked (aiohttp and urllib), they do not create a span if they can't build a request due to an invalid URL.

Thus, by the time we reach send we always have a PreparedRequest object we can use for the request_hook callback argument.
