### ISSUE TITLE
opentelemetry-instrumentation-urllib3

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-python-contrib#937]

**Comment by nstawski** [comment]
I would like to take this issue.

**Comment by nstawski** [comment]
Upd: having a closer look at the code, looks like this issue is already addressed and no changes need to be done for it. https://github.com/nstawski/ns-opentelemetry-python-contrib/blob/9e539391b21f741fc0cdc2b139e652199776bca6/instrumentation/opentelemetry-instrumentation-urllib3/src/opentelemetry/instrumentation/urllib3/__init__.py#L174
